%% Class natureprintstyle
%% Written by Brendon Higgins, blhiggins@gmail.com
%% v1.0.1 24 July 2009
%% Based on class nature, written by Peter Czoschke, czoschke@mrl.uiuc.edu
%%
%% A drop-in replacement for the nature.cls class, used for Nature letter and
%% article preprints, that approximates Nature's style in print.
%%
%% Note that \includegraphics commands are not ignored, as they are in
%% nature.cls.
%%
%% This class may be particularly handy if an author finds it annoying to
%% read the single column format of the Nature preprint style.
%%
%% I created this class for personal purposes and without any connection
%% to the Nature Publishing Group.  I in no way claim that documents generated
%% with this file fully comply with their current style requirements.
%% I disclaim any responsibility for the use of this file heretofore.
%%
%% ------------------------------------
%%
%% See nature.cls and its documentation for notes on usage.
%%
%% The file nature-template.tex, an example for the nature.cls class, should
%% also work with this class. Simply replace \documentclass{nature} with
%% \documentclass{natureprintstyle}.

\ProvidesClass{natureprintstyle}[24/7/2009 v1.0.1]
\typeout{A class for emulating the style of Nature in print when writing preprints for the journal Nature}
\typeout{Written by Brendon Higgins}
\typeout{Based on nature.cls by Peter Czoschke}
\typeout{ }

\LoadClass[9pt,twocolumn]{extarticle}
\RequirePackage{cite}
\RequirePackage{times}
\RequirePackage{fullpage}
\RequirePackage{ifthen}
\RequirePackage[left=1cm,top=2.5cm,right=1.53cm,bottom=2cm,nohead,nofoot]{geometry}
\RequirePackage{scalefnt}
\RequirePackage{type1cm}

%% make labels in bibliobraphy be #.
\renewcommand\@biblabel[1]{#1.}

%% make citations be superscripts, taken from citesupernumber.sty
\def\@cite#1#2{$^{\mbox{\scriptsize #1\if@tempswa , #2\fi}}$}

%% Some style parameters
\setlength{\parindent}{0.20in}
\newcommand{\spacing}[1]{\renewcommand{\baselinestretch}{#1}\large\normalsize}

%% Redefine \maketitle for Nature style
\def\@maketitle{%
  \newpage\spacing{1}\setlength{\parskip}{12pt}%
    {\rule{\textwidth}{1pt} \par}%
    {\scalefont{2.7}\bfseries\noindent\sloppy%
        \textsf{\begin{flushleft}\@title\end{flushleft}%
    } \par}%
    {\scalefont{1.22}\noindent\sloppy \textsf{\@author}}%
}

%% Define the affiliations environment, list each institution as an \item
%% Put after \maketitle
\newenvironment{affiliations}{%
    \let\olditem=\item
    \renewcommand\item[1][]{$^{\arabic{enumi}}$\stepcounter{enumi}}
    \setcounter{enumi}{1}%
    \setlength{\parindent}{0in}%
    \slshape\sloppy%
    \sffamily%
    \scalefont{0.83}
    }{\par\vspace{12pt}\let\item=\olditem}

%% Redefine the abstract environment to be the first bold paragraph
\renewenvironment{abstract}{%
    \setlength{\parindent}{0in}%
    \setlength{\parskip}{0in}%
    \bfseries%
    }{\par}

%% Redefine the \section command.
\renewcommand{\section}{\@startsection {section}{1}{0pt}%
    {12pt}{0pt}%
    {\sffamily\bfseries}%
    }
\renewcommand{\subsection}{\@startsection {subsection}{2}{0pt}%
    {0pt}{-0.5em}%
    {\bfseries}*%
    }

%% Define the methodssummary environment.  Use \subsection to separate. These come before methods.
\newenvironment{methodssummary}{%
    \section*{METHODS SUMMARY}%
    \setlength{\parskip}{0pt}%
    \scalefont{0.93}
    }{}

%% Define the methods environment.  Use \subsection to separate.
\newenvironment{methods}{%
    \section*{METHODS}%
    \setlength{\parskip}{0pt}%
    \scalefont{0.93}
    }{}

%% No heading for References section, but eat up the extra space from \section command
\renewcommand\refname{\vspace{-6pt}}

\let\oldthebibliography=\thebibliography
  \let\endoldthebibliography=\endthebibliography
  \renewenvironment{thebibliography}[1]{%
    \begin{oldthebibliography}{#1}%
      \sffamily%
      \scalefont{0.83}%
      \setlength{\parskip}{-3pt}%
%  \setcounter{enumiv}{ 30}%
  }%
  {%
    \end{oldthebibliography}%
  }

\let\oldbibitem=\bibitem
\renewcommand{\bibitem}[1]{\vspace{-0.15ex}\oldbibitem{#1}}
%% bibitem takes an optional parameter, so this might be broken.


%% Define the addendum environment for Supplementary Info, Acknowledgements, etc.
\newenvironment{addendum}{%
    \setlength{\parindent}{0in}%
    \scalefont{0.93}%
    \begin{list}{Acknowledgements}{%
        \setlength{\leftmargin}{0in}%
        \setlength{\listparindent}{0in}%
        \setlength{\labelsep}{0em}%
        \setlength{\labelwidth}{0in}%
        \setlength{\itemsep}{12pt}%
        \let\makelabel\addendumlabel}
    }
    {\end{list}\par\vfill}

\newcommand*{\addendumlabel}[1]{\textbf{#1}\hspace{1em}}

%% Figures and tables:
%% The \includegraphics command is respected.
%% Tables should all be moved to the end of the document
%% manually.

\renewcommand{\figurename}{Figure}
\renewcommand{\tablename}{Table}

%% Change the way captions are formatted. Based on a tip by Jakob Schiotz.
%% http://dcwww.camd.dtu.dk/~schiotz/comp/LatexTips/LatexTips.html
\long\def\@makecaption#1#2{%
  \vskip\abovecaptionskip
  \sbox\@tempboxa{{\sffamily\textbf{\scalefont{0.93}#1 $\vert$}} #2}%
  \ifdim \wd\@tempboxa >\hsize
    {\scalefont{0.93}{\sffamily\textbf{\scalefont{0.93}#1 $\vert$}} #2\par}
  \else
    \hbox to\hsize{\hfil\box\@tempboxa\hfil}%
  \fi
  \vskip\belowcaptionskip}
